"use strict";
exports.__esModule = true;
var express = require("express");
var bodyParser = require("body-parser");
var cookieParser = require("cookie-parser");
var cors = require("cors");
require('dotenv').config();
var signup_1 = require("./api/accounts/signup");
var login_1 = require("./api/accounts/login");
var session_1 = require("./api/accounts/session");
var calls_1 = require("./api/calls");
var adm_1 = require("./api/accounts/adm");
var app = express();
app.use(bodyParser.urlencoded({ extended: true }));
app.use(bodyParser.json());
app.use(cookieParser());
app.use(cors());
var port = process.env.PORT || 5000;
app.post('/api/signup', signup_1["default"]);
app.post('/api/login', login_1["default"]);
app.get('/api/session', session_1["default"]);
app.get('/api/calls', calls_1["default"]);
app.get('/api/calls/mycalls', calls_1.listUsersCall);
app.post('/api/calls', calls_1.createCall);
app.post('/api/call/join', calls_1.joinCall);
app.post('/api/call/moderate', calls_1.moderateCall);
app.get('/api/adm/users', adm_1["default"]);
app.put('/api/adm/user', adm_1.updateUser);
app.put('/api/adm/user/password', adm_1.changeUserPassword);
app["delete"]('/api/adm/user', adm_1.deleteUser);
app.listen(port, function () { return console.log("Listening on port " + port); });
